### ISSUE TITLE
Helm upgrade fails due to breaking change in MinIO secret key names

### ISSUE THREAD

**Issue by RiccardoTOTI** [kestra-io/helm-charts#56] opened 2024-10-08 10:21 UTC
### Expected Behavior

The Helm upgrade should handle the secret key changes without requiring a full reinstallation.

### Actual Behaviour

The upgrade fails due to the mismatch in secret key names, leading to the need for a full uninstall and reinstall of the application.

The following error was encountered:

```
Error: UPGRADE FAILED: execution error at (kestra/charts/minio/templates/standalone/deployment.yaml:29:40): 
PASSWORDS ERROR: The secret "kestra-minio" does not contain the key "root-user"
```

In the new version of the Bitnami MinIO chart, there is a breaking change where the keys for the MinIO secret have been renamed:
- Old keys: `rootUser` and `rootPassword`
- New keys: `root-user` and `root-password`

### Steps To Reproduce

1. Deploy Kestra in standalone mode with version 0.18.
2. Ensure MinIO version is `minio:RELEASE.2022-10-24T18-35-07Z`.
3. Run the Helm upgrade command to update to `minio:2024.10.2-debian-12-r0`:

   ```bash
   helm upgrade --install <release-name> <chart-name>
   ```

### Environment Information

- **Starting Kestra version:** 0.18
- **Helm chart version:** [v0.18.0](https://github.com/kestra-io/kestra/releases/tag/v0.18.0)
- **Kubernetes version:** v1.26.15
- **MinIO version before upgrade:** `minio:RELEASE.2022-10-24T18-35-07Z`
- **MinIO version after upgrade:** `minio:2024.10.2-debian-12-r0`
- **Finish Kestra version:** 0.19.1

**Comment by loicmathieu** [comment] 2024-10-08 15:08
@anna-geller we may want to add it to the list of breaking change for 0.19 for those who use MinIO.

@RiccardoTOTI we use the MinIO chart as a dependency of our chart, there is nothing we can do to tackle this issue, and as you pointed out this is due to a breaking change in the MinIO Chart.
As it's not complex to change the attribute in your Helm values, I'll close this issue.

Thanks for reporting, users struggling with the same issue will easily be able to find the cause and fix it ;)

**Closed by loicmathieu** 2024-10-08 15:08 UTC
Labels: bug
